FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8080
RUN useradd -r -u 10001 appuser \
  && chown -R appuser:appuser /app
USER appuser
ENTRYPOINT ["java","-jar","/app/app.jar"]
