variable "resource_group_name" {
  type        = string
  description = "Name of the Azure Resource Group to create"
  default     = "my-aks-rg"
}

variable "location" {
  type        = string
  description = "Azure region for resources"
  default     = "eastus"
}

variable "cluster_name" {
  type        = string
  description = "AKS cluster name"
  default     = "my-aks-cluster"
}

variable "vnet_cidr" {
  type        = string
  description = "CIDR block for the Virtual Network"
  default     = "10.0.0.0/16"
}

variable "aks_subnet_cidr" {
  type        = string
  description = "CIDR block for the AKS subnet"
  default     = "10.0.1.0/24"
}

variable "acr_name" {
  type        = string
  description = "Azure Container Registry name (lowercase, 5-50 chars, globally unique)"
  default     = "demoacr12345"

  validation {
    condition     = length(var.acr_name) >= 5 && length(var.acr_name) <= 50 && can(regex("^[a-z0-9]+$", var.acr_name))
    error_message = "acr_name must be 5-50 chars, lowercase letters and numbers only."
  }
}

variable "acr_sku" {
  type        = string
  description = "ACR SKU (Basic | Standard | Premium)"
  default     = "Basic"

  validation {
    condition     = contains(["Basic", "Standard", "Premium"], var.acr_sku)
    error_message = "acr_sku must be one of: Basic, Standard, Premium."
  }
}

variable "node_count" {
  type        = number
  description = "Number of nodes in the default node pool"
  default     = 3

  validation {
    condition     = var.node_count > 0
    error_message = "node_count must be greater than 0."
  }
}

variable "vm_size" {
  type        = string
  description = "VM size for AKS nodes"
  default     = "Standard_DS2_v2"
}

variable "api_server_authorized_ip_ranges" {
  type        = list(string)
  description = "CIDR ranges allowed to access the AKS API server; empty list allows all (not recommended for production)"
  default     = []
}

variable "environment" {
  type        = string
  description = "Environment name (dev, test, prod)"
  default     = "dev"

  validation {
    condition     = contains(["dev", "test", "prod"], var.environment)
    error_message = "environment must be one of: dev, test, prod."
  }
}

variable "kubernetes_version" {
  type        = string
  description = "Kubernetes version to use for the AKS cluster"
  default     = "1.28"
}

variable "enable_log_analytics" {
  type        = bool
  description = "Enable Log Analytics for AKS cluster"
  default     = true
}

variable "addon_http_application_routing_enabled" {
  type        = bool
  description = "Enable HTTP application routing"
  default     = false
}

variable "addon_azure_policy_enabled" {
  type        = bool
  description = "Enable Azure Policy for Kubernetes"
  default     = false
}

variable "enable_app_gateway_ingress" {
  type        = bool
  description = "Enable Application Gateway Ingress Controller (AGIC)"
  default     = false
}

variable "app_gateway_subnet_cidr" {
  type        = string
  description = "CIDR block for the Application Gateway subnet"
  default     = "10.0.2.0/24"
}

variable "app_gateway_name" {
  type        = string
  description = "Application Gateway name (optional, autogenerated when empty)"
  default     = ""
}
